AWSTemplateFormatVersion: '2010-09-09'
Description: URL Shortener App - Lab Infra (S3 Static Website, S3 Logging, DynamoDB)

Parameters:
  WebsiteBucketName:
    Type: String
    Default: aws9-nadia-shortener-site-2025
    Description: Name for the static website S3 bucket (must be globally unique)
  LogsBucketName:
    Type: String
    Default: aws9-nadia-shortener-logs-2025
    Description: Name for the S3 bucket to store CloudFront logs (must be globally unique)
  TableName:
    Type: String
    Default: ShortUrls
    Description: DynamoDB table name for short URL mapping

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref WebsiteBucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      Tags:
        - Key: Project
          Value: url-shortener

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub arn:aws:s3:::${WebsiteBucketName}/*

  LogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref LogsBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: url-shortener-logs

  ShortUrlTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Project
          Value: url-shortener

Outputs:
  WebsiteBucketName:
    Description: "Static website S3 bucket name"
    Value: !Ref WebsiteBucketName
  LogsBucketName:
    Description: "CloudFront logs S3 bucket name"
    Value: !Ref LogsBucketName
  DynamoDBTable:
    Description: "Short URL DynamoDB table name"
    Value: !Ref TableName
